### ISSUE TITLE
createAccount iOS not complete registration

### ISSUE THREAD

**Issue by dariomalfatti-centropaghe** [willnaoosmith/React-native-sip-pjsip#9]
Hi, can I ask you a question because I'm stuck with react-native-pjsip and no one reply on datso GitHub project? I see that you are active within the project and maybe you can help me.

In practice, with Android, everything works, with iOS createAccount stay in 'PJSIP_SC_TRYING' status. Looking at the SIP service log, it starts the registration but when the sip service asks to send back the credentials, pjsip not reply and stay in trying status. Can you exec createAaccount successfully with iOS? A release that I build in April works, but (I think) after few Apple updates and increasing the iOS target, it doesn't work anymore.

Thank you

**Comment by willnaoosmith** [comment]
Hi!

The code that runs on IOS and the code that runs on Android are severely different from each other (The code that runs on IOS is on the `node_modules/react-native-pjsip/ios/` folder when the project is compiled. Differelty from the code that runs on Android, wich comes with the repository already, and is on the  `node_modules/react-native-pjsip/Android` folder).

One thing that can happen, is that react-native-pjsip project runs on 2.8 pjsip.
It simply does not work for me, so this project runs on 2.7.9 pjsip, wich runs fine.

You can try seeing on the apple simulator logs of your apllication, BUT, it would be too much information.

Try this repository, it works perfectly for me.

If not, you can try this one: [react-native-sip](https://github.com/florindumitru/react-native-sip). Wich was made in mind to run on IOS more than on Android.

**Comment by dariomalfatti-centropaghe** [comment]
Thank you for your reply.
I tried to install your version but it doesn't work to me. The registration stay in TRYING.
I can't install react-native-sip, it raise an exception trying to download pjsip from pjsip.org with an url not found.
Any other advise? Which version of ios sdk are you using as target? Thanks

**Comment by willnaoosmith** [comment]
I'm using SDK 28 on this project.

You already tried looking on your SIP server what's happening?

Otherwise, running `adb logcat` on a terminal and looking for `pjsipservice` or something like this may help to find what's happening.

**Comment by dariomalfatti-centropaghe** [comment]
The problem was just with iOS but updating Vialer I solved the problem. Thank you for the support.
